server:
  port: 8123
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: changmoonTLS/cert.p12
    key-store-password: {password}
  address: 0.0.0.0
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

###### jwt ######
jwt:
  header: Authorization
  secret: {jwt_secret}

###### spring Jpa config #####

---
#### local ####
spring:
  profiles: local
    #active: local
  datasource:
    url: {db_url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 122333
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---

#### deploy ####
spring:
  profiles:
    active: prod
  datasource:
#    url:  {db_url}
    url: j {db_url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root1
      password: root1
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher






